config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

    path('product/<slug:slug>/detail/', views.ProductDetailView.as_view(), name='product_detail'),

    # Cart
    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/<int:pk>/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/remove/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/<int:pk>/delete/', views.CartDeleteView.as_view(), name='cart_delete'),

    path('product/<slug:slug>/comment/', views.CommentView.as_view(), name='comment'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/update/photo/', views.UpdateProfileImageView.as_view(), name='update_photo'),
    path('profile/update/password/', views.PasswordChangeView.as_view(), name='password_change'),
    path('profile/update/info/', views.UpdateProfileView.as_view(), name='update_info'),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

templates/_components/footer.html
{% load static %}

<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum
                tempor no vero est magna amet no</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                    <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary">Sign Up</button>
                            </div>
                        </div>
                    </form>
                    <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                by
                <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'shop/img/payments.png' %}" alt="">
        </div>
    </div>
</div>

templates/_components/messages.html
<!-- Modal -->
<div class="container-fluid">
{% if messages %}
    {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        {% if message.tags == 'success' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: green">
                                Muvafaqqiyatli!
                            </h5>
                        {% elif message.tags == 'warning' %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: orange">
                                Ogohlantirish!
                            </h5>
                        {% else %}
                            <h5 class="modal-title text-uppercase" id="exampleModalLongTitle" style="color: red">
                                Xatolik!
                            </h5>
                        {% endif %}
                    </div>
                    <div class="modal-body">
                        <p style="color: black">{{ message }}</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close">Close</button>
                        <a href="{% url 'shop:home' %}" type="button" class="btn btn-primary">Bosh sahifa</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}
</div>

<!-- Script to trigger modal on page load -->
{% if messages %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endif %}

<script>
$(document).ready(function(){
    $('#messageModal').modal('show');

    // close tugmasi bosilganda modalni yopish
    $('#close').on('click', function() {
        $('#messageModal').modal('hide');
    });
});
</script>

templates/_components/navbar.html
{% load static %}

<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse"
               href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    {% for category in categories %}
                        <a href="#{{ category.slug }}" class="nav-item nav-link">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Mini</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'shop:home' %}" class="nav-item nav-link active">Home</a>
                        <a href="shop.html" class="nav-item nav-link">Shop</a>
                        <a href="detail.html" class="nav-item nav-link">Shop Detail</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i
                                    class="fa fa-angle-down mt-1"></i></a>
                            <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                <a href="checkout.html" class="dropdown-item">Checkout</a>
                            </div>
                        </div>
                        <a href="contact.html" class="nav-item nav-link">Contact</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a href="" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">0</span>
                        </a>
                        <a href="{% url 'shop:cart_list' %}" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <small id="cart-count_nav" class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">{{ request.session.cart|length }}</small>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

templates/_components/script.html
{% load static %}

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'shop/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'shop/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'shop/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'shop/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'shop/js/main.js' %}"></script>
<script src="{% static 'shop/js/custom.js' %}"></script>


<script>
    function showToast(message, title = "Notification") {
        var toastId = 'toast-' + Math.random().toString(36).substring(2, 9);

        var toastHTML = `
        <div id="${toastId}" class="toast show" role="alert" aria-live="assertive" aria-atomic="true" style="max-height: 45px; background-color: #e2eaf7">
            <div class="toast-content">
                ${title}: ${message}
            </div>
        </div>`;

        document.getElementById('toast-container').insertAdjacentHTML('beforeend', toastHTML);

        // Remove toast after a few seconds
        setTimeout(() => {
            document.getElementById(toastId).remove();
        }, 3000);
    }


    function updateCart(event, action, productId) {
        event.preventDefault();

        var url = '/cart/' + productId + '/' + action + '/';
        fetch(url, {
            method: 'GET',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            }
        })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    const btn_minus = document.getElementById('btn_minus');

                    if (action === 'remove' && data.message === "Cartdan o'chirildi") {
                        btn_minus.disabled = true;
                    } else if (action === 'remove') {
                        btn_minus.disabled = false;
                    }

                    console.log(data.message);

                    showToast(data.message);

                    document.getElementById('cart-count_top').innerText = Object.keys(data.cart).length;
                    document.getElementById('cart-count_nav').innerText = Object.keys(data.cart).length;
                }
            })
            .catch(error => console.log('Error:', error));
    }
</script>

templates/_components/style.html
{% load static %}

<!-- Favicon -->
{#<link href="{% static 'shop/img/favicon.ico' %}" rel="icon">#}

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'shop/lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'shop/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Font Awesome -->
<link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
/>


<style>
    .account-settings .user-profile {
        margin: 0 0 1rem 0;
        padding-bottom: 1rem;
        text-align: center;
    }

    .account-settings .user-profile .user-avatar {
        margin: 0 0 1rem 0;
    }

    .account-settings .user-profile .user-avatar img {
        width: 150px;
        height: 150px;
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;
    }

    .account-settings .user-profile h5.user-name {
        margin: 0 0 0.5rem 0;
        font-size: 1.6rem;
    }

    .account-settings .user-profile h6.user-email {
        margin: 0;
        font-size: 1rem;
        color: #9fa8b9;
    }

    .account-settings .about {
        margin: 2rem 0 0 0;
        text-align: center;
    }

    .account-settings .about h5 {
        margin: 0 0 15px 0;
        color: #007ae1;
    }

    .form-control {
        border: 1px solid #cfd1d8;
        -webkit-border-radius: 2px;
        -moz-border-radius: 2px;
        border-radius: 5px;
        background: #ffffff;
        color: #2e323c;
    }

    .card {
        background: #ffffff;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        border: 0;
        margin-bottom: 1rem;
    }

    .change-password-pen:hover {
        color: #FFD333;
        transition: all .5s;
    }
</style>

<style>
  #toast-container {
    position: fixed;
    top: 20px;
    right: 20px;
    z-index: 1050;
    display: flex;
    flex-direction: column;
    align-items: flex-end;
}

.toast {
    border-radius: 8px;
    padding: 10px 15px;
    margin-bottom: 10px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.6);
    animation: slide-in 0.5s ease-out;
    font-family: Arial, sans-serif;
    font-size: 14px;
}

.toast-content {
    font-size: 16px;
    color: #db910f;
}

@keyframes slide-in {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

</style>

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'shop/css/style.css' %}" rel="stylesheet">
<link href="{% static 'shop/css/custom.css' %}" rel="stylesheet">

templates/_components/topbar.html
{% load static %}

<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="">About</a>
                <a class="text-body mr-3" href="">Contact</a>
                <a class="text-body mr-3" href="">Help</a>
                <a class="text-body mr-3" href="">FAQs</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My
                        Account
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'user:profile' %}" class="dropdown-item" type="button">My Profile({{ request.user.username }})</a>
                            <a href="{% url 'user:logout' %}" class="dropdown-item" style="color: red" type="button">Logout</a>
                        {% else %}
                            <a href="{% url 'user:login' %}" class="dropdown-item" type="button">Login</a>
                            <a href="{% url 'user:register' %}" class="dropdown-item" type="button">Register</a>
                        {% endif %}
                    </div>
                </div>
                <div class="btn-group mx-2">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">USD
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">EUR</button>
                        <button class="dropdown-item" type="button">GBP</button>
                        <button class="dropdown-item" type="button">CAD</button>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">EN
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">FR</button>
                        <button class="dropdown-item" type="button">AR</button>
                        <button class="dropdown-item" type="button">RU</button>
                    </div>
                </div>
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span id="cart-count_top" class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">{{ request.session.cart|length }}</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Mini</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                                <span class="input-group-text bg-transparent text-primary">
                                    <i class="fa fa-search"></i>
                                </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Service</p>
            <h5 class="m-0">+012 345 6789</h5>
        </div>
    </div>
</div>