config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

    path('product/<slug:slug>/detail/', views.ProductDetailView.as_view(), name='product_detail'),

    # Cart
    path('cart/', views.CartListView.as_view(), name='cart_list'),
    path('cart/<int:pk>/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/remove/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('cart/<int:pk>/delete/', views.CartDeleteView.as_view(), name='cart_delete'),

    path('product/<slug:slug>/comment/', views.CommentView.as_view(), name='comment'),
]

shop/models.py
from django.db import models
from user.models import User
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="categories/", blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        verbose_name = "Kategoriya"
        verbose_name_plural = "Kategoriyalar"

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return self.image.url
        return False

    def get_products(self):
        return self.products.filter(available=True)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    information = models.TextField(null=True, blank=True, default="Ma'lumot yo'q")

    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Narx: $")
    measurement_unit = models.CharField(max_length=50, choices=[
        ('kg', 'Kilogram'),
        ('dona', 'Dona'),
        ('l', 'Litr'),
        ('m', 'Metr'),
    ], default='kg', verbose_name="Birlik")
    discount = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    is_discount = models.BooleanField(default=False)
    stock = models.IntegerField()
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Mahsulot'
        verbose_name_plural = 'Mahsulotlar'

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return self.image.url
        return False

    def current_price(self):
        if self.is_discount:
            return round(self.price * (1 - self.discount/100), 2)
        return self.price

    def get_rating(self):
        comments = self.comments.all()
        if comments.exists():
            return '{:.2f}'.format(sum(comment.rating for comment in comments) / comments.count())
        return 0

    def get_rating2x(self):
        return self.get_rating() * 2


class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    rating = models.PositiveIntegerField(default=1, choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'Sharh {self.user.username} tomonidan {self.product.name} uchun'

shop/forms.py
from django import forms
from django.core.exceptions import ValidationError


class CommentForm(forms.Form):
    rating = forms.IntegerField(
        required=True,
        label="Your Rating",
        min_value=1,
        max_value=5,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'id': 'rating',
            'min': '1',
            'max': '5',
            'type': 'hidden',
            'value': 1
        })
    )

    content = forms.CharField(
        required=True,
        label="Your Review",
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'id': 'content',
            'rows': 5,
            'cols': 30,
            'name': 'content',
            'placeholder': 'Typing here...'
        })
    )

    def clean_rating(self):
        rating = self.cleaned_data.get('rating')
        if not (1 <= rating <= 5):
            raise ValidationError("Mahsulotni 1 dan 5gacha baholang")
        return rating

shop/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import JsonResponse

from .models import Category, Product, Comment
from .forms import CommentForm


class HomeView(View):
    def get(self, request):
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)[:8]
        context = {
            'title': 'Bosh sahifa',
            'categories': categories,
            'products': products,
        }
        return render(request, 'shop/index.html', context)


class ProductDetailView(View):
    def get(self, request, slug):
        product = Product.objects.get(slug=slug)
        categories = Category.objects.all()

        comment_form = CommentForm()
        context = {
            'title': product.name,
            'product': product,
            'categories': categories,
            'comment_form': comment_form,
            'product_cart': request.session.get('cart', {}).get(str(product.id), 0)
        }
        return render(request,'shop/product_detail.html', context)


class CommentView(LoginRequiredMixin, View):
    def post(self, request, slug):
        product = Product.objects.get(slug=slug)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            Comment.objects.create(
                content=comment_form.cleaned_data['content'],
                rating=comment_form.cleaned_data['rating'],
                user=request.user,
                product=product,
            )
            messages.success(request, "Thank you for a comment")
            return redirect('shop:product_detail', slug=slug)
        messages.error(request, "Izoh saqlanmadi.")
        return redirect('shop:product_detail', slug=slug)


class CartListView(View):
    def get(self, request):
        cart = request.session.get('cart', {})
        products = Product.objects.filter(id__in=cart.keys())
        full_price = 0
        for product in products:
            product.quantity = cart[str(product.id)]
            product.total_price = float(product.current_price()) * cart[str(product.id)]
            full_price += product.total_price
        context = {
            'title': 'Savat',
            'products': products,
            'full_price': full_price,
        }
        return render(request,'shop/cart.html', context)


class CartAddView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)

        if cart.get(p_id):
            cart[p_id] += 1
            message = "Cart yangilandi"
        else:
            cart[p_id] = 1
            message = "Cartga qo'shildi"

        request.session['cart'] = cart
        return JsonResponse({'status': 'success', 'cart': cart, 'message': message})


class CartRemoveView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)
        p = cart.get(p_id)
        if p:
            if p > 1:
                cart[p_id] -= 1
                message = "Cart yangilandi"
            elif p == 1:
                del cart[p_id]
                message = "Cartdan o'chirildi"
            else:
                message = "Mavjud emas"
        else:
            message = "Cartda mavjud emas"
        print("Remove ****************************")
        request.session['cart'] = cart
        return JsonResponse({'status': 'success', 'cart': cart, 'message': message})


class CartDeleteView(View):
    def get(self, request, pk):
        cart = request.session.get('cart', {})
        p_id = str(pk)
        if p_id in cart:
            del cart[p_id]
        request.session['cart'] = cart
        return redirect('shop:cart_list')

shop/templates/shop/cart.html
{% extends 'base.html' %}
{% load cart_tags %}

{% block content %}
	<div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for product in products %}
                    	<tr>
                            <td class="align-middle"><img src="{{ product.get_image }}" alt="" style="width: 50px;"> {{ product.name }}</td>
                            <td class="align-middle">${{ product.current_price }}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button id="btn_minus" {% if product_cart == 0 %} disabled {% endif %}
                                                class="btn btn-sm btn-primary btn-minus"
                                                onclick="updateCart(event, 'remove', '{{ product.pk }}'); showButton()">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>

                                    <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center"
                                           value="{{ product.quantity }}">

                                    <div class="input-group-btn">
                                        <button id="btn_minus"
                                                class="btn btn-sm btn-primary btn-plus"
                                                onclick="updateCart(event, 'add', '{{ product.pk }}'); showButton()">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">${{ product.total_price }}</td>
                            <td class="align-middle"><a href="{% url 'shop:cart_delete' product.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="pt-2">
                    <a id="cart_update" href="{% url 'shop:cart_list' %}" class="disabled btn btn-block btn-primary font-weight-bold my-3 py-3 cart_update">Update Cart</a>
                </div>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>${{ full_price }}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ full_price|price_with_shipping:10 }}</h5>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function showButton() {
            const button = document.getElementById('cart_update');
            button.classList.remove('disabled');
        }
    </script>

{% endblock %}

shop/templates/shop/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Carousel Start -->
    {% include 'components/carousel.html' %}
    <!-- Carousel End -->


    <!-- Featured Start -->
    {% include 'components/featured.html' %}
    <!-- Featured End -->


    <!-- Categories Start -->
    {% include 'components/categories.html' %}
    <!-- Categories End -->


    <!-- Products Start -->
    {% include 'components/products1.html' %}
    <!-- Products End -->


    <!-- Offer Start -->
    {% include 'components/offer.html' %}
    <!-- Offer End -->


    <!-- Products Start -->
    {% include 'components/products2.html' %}
    <!-- Products End -->


    <!-- Vendor Start -->
    {% include 'components/vendor.html' %}
    <!-- Vendor End -->
{% endblock %}